import { useState } from "react";
import type { CompleteInspectorRun, DataRef } from "../inspector/types";
const WINDOW = 32;
export default function LaneView({ run, physical = false, selected, onSelect }: { run: CompleteInspectorRun; physical?: boolean; selected?: DataRef | null; onSelect?: (ref: DataRef) => void }) {
  const [lane, setLane] = useState(0); const [start, setStart] = useState(0);
  const rows = physical ? run.laneInspection.physicalBits[lane] : run.laneInspection.pcsSymbols[lane];
  const end = Math.min(rows.length, start + WINDOW);
  const stage = physical ? "physical-lanes" : "pcs-lanes"; const bufferId = physical ? "pmd-lanes" : "pcs-lanes";
  return <section className="lane-view" aria-label={physical ? "Physical lane values" : "PCS lane values"}><p>{physical ? "Reference PMA mapping with absolute output bit, source PCS lane, and mux phase." : "PCS lane symbols serialize bit zero first."}</p><label>Lane <select value={lane} onChange={(event) => { setLane(Number(event.target.value)); setStart(0); }}>{Array.from({ length: physical ? 4 : 16 }, (_, value) => <option key={value} value={value}>{physical ? "PMD" : "PCS"} lane {value}</option>)}</select></label><p>Showing {start + 1}–{end} of {rows.length} values</p><div className="lane-rows">{rows.slice(start, end).map((value, offset) => { const absolute = start + offset; const source = physical ? run.laneInspection.physicalSourcePcsLane[lane][absolute] : undefined; const ref = { stage, bufferId, start: physical ? lane * rows.length + absolute : lane * rows.length + absolute, count: 1 } as DataRef; return <button type="button" aria-pressed={selected?.stage === stage && selected.bufferId === bufferId && selected.start === ref.start} key={absolute} onClick={() => onSelect?.(ref)} className="data-window__value"><small>{physical ? `Output bit ${run.laneInspection.physicalStartAbsoluteBit + absolute}` : `Symbol ${absolute}`}</small><code>{physical ? `bit ${value} · PCS ${source} · phase ${(run.laneInspection.physicalInitialPhase + run.laneInspection.physicalStartAbsoluteBit + absolute) % 4}` : `0x${value.toString(16).padStart(3, "0")} · ${value.toString(2).padStart(10, "0").split("").reverse().join("")}`}</code></button>; })}</div><div className="data-window__controls"><button type="button" disabled={start === 0} onClick={() => setStart(Math.max(0, start - WINDOW))}>Previous</button><button type="button" disabled={end === rows.length} onClick={() => setStart(Math.min(rows.length - 1, start + WINDOW))}>Next</button></div></section>;
}
